[package]
name = "blockchain-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.11.0-pre.4"
chrono = "0.4.39"
hex = "0.4.3"
clap = { version = "4.5.26", features = ["derive"] }
rand = "0.9.0-beta.1"
